# Generated by Django 4.0.1 on 2022-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='moviessubscribed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='typeofcontentprefered',
            field=models.TextField(null=True),
        ),
    ]
