# Generated by Django 4.0.1 on 2022-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_age_user_gender_user_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default='guest'),
        ),
    ]
